name: Deploy Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

permissions:
  pages: write # Allow workflow to create github-pages
  id-token: write # Allow actions/deploy-pages to request permission

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn demoBuild

      - name: Set up github-pages
        uses: actions/configure-pages@v4

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './demo/dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
